name: ðŸŽ‰ Meetup announce
on:
  workflow_dispatch:
    inputs:
      backgroundImg:
        description: "Do you want to use a custom image as background?"
        required: false
      title:
        description: "What is the title of the event?"
        required: true
      date:
        description: "What is the date of event?"
        required: true
        default: "28 septembre 2022"

jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        with:
          version: 7
          run_install: true
      - run: echo $WORKFLOW_INPUT > input-props.json
        name: Preparing props
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: pnpm remotion render src/index.tsx Meetup out/meetup-${{github.run_id}}.mp4 --props="./input-props.json"
        name: ðŸŽ¬ Generating video
        working-directory: packages/remotion-components
      - run: pnpm remotion still src/index.tsx Meetup --props="./input-props.json" --frame 119
        name: ðŸ“· Generating last image
        working-directory: packages/remotion-components
      - uses: actions/upload-artifact@v3
        with:
          name: meetup-${{github.run_id}}
          path: packages/remotion-components/out
