name: ðŸ¹ Sponsor
on:
  workflow_dispatch:
    inputs:
      companyName:
        description: "What is the name of the sponsor company?"
        required: true
        default: "Example"
      backgroundImg:
        description: "If you want to use custom image for background"
        required: false
      localisation:
        description: "What is the localisation of the sponsor company ?"
        required: false
      sponsorLogo:
        description: "If you want to use custom image for sponsor logo"
        required: false
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          cache: "pnpm"
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 7
          run_install: true
      - run: echo $WORKFLOW_INPUT > input-props.json
        name: Preparing props
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: pnpm remotion render src/index.tsx Sponsor out/sponsor-${{github.event.inputs.companyName}}.mp4 --props="./input-props.json"
        name: ðŸŽ¬ Generating video
      - run: pnpm remotion still src/index.tsx Sponsor --props="./input-props.json" --frame 119
        name: ðŸ“· Generating last image
      - uses: actions/upload-artifact@v3
        with:
          name: sponsor-${{github.event.inputs.companyName}}
          path: out
