name: ðŸŽ¤ Talk
on:
  workflow_dispatch:
    inputs:
      speakersNames:
        description: "What are the name of the speakers?"
        required: true
        default: "John Doe & Terry Pratchett"
      talkTitle:
        description: "What is the title of the talk?"
        required: true
        default: "Is JS an awesome programing language?"
      titleSize:
        description: "What is the title of the talk?"
        required: false
        default: "80px"
      speakerPicture:
        description: "Url of the profile picture of the speaker"
        required: false
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        with:
          version: 7
          run_install: true
      - run: echo $WORKFLOW_INPUT > input-props.json
        working-directory: packages/remotion-components
        name: Preparing props
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: pnpm remotion render src/index.tsx TalkWithoutPicture out/talk-${{github.run_id}}.mp4 --props="./input-props.json"
        name: ðŸŽ¬ Generating video
        working-directory: packages/remotion-components
      - run: pnpm remotion still src/index.tsx TalkWithoutPicture --props="./input-props.json" --frame 119
        name: ðŸ“· Generating last image
        working-directory: packages/remotion-components
      - uses: actions/upload-artifact@v3
        with:
          name: talk-${{github.run_id}}
          path: packages/remotion-components/out
